apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  labels:
    app: temporal
spec:
  replicas: 3
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: talk2anyi/hello-workflow
          ports:
            - containerPort: 7233
              name: grpc
            - containerPort: 8088
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  type: ClusterIP
  selector:
    app: temporal
  ports:
    - name: grpc
      port: 7233
      targetPort: grpc
    - name: http
      port: 8088
      targetPort: http
